import jsPDF from "jspdf";

export const exportNotePDF = (note) => {

  const doc = new jsPDF();

  let y = 20;

  doc.setFontSize(22);
  doc.setTextColor(40,40,40);

  doc.text(note.title,20,y);

  y += 12;

  doc.line(20,y,190,y);

  y += 12;

  if(note.subjectName){

    doc.setFontSize(12);

    doc.text(

      `Subject : ${note.subjectName}`,

      20,

      y

    );

    y += 10;

  }

  if(note.dueDate){

    doc.text(

      `Due : ${new Date(note.dueDate).toLocaleString()}`,

      20,

      y

    );

    y += 12;

  }

  doc.setFontSize(14);

  const lines = doc.splitTextToSize(

    note.content,

    170

  );

  doc.text(lines,20,y);

  doc.setFontSize(10);

  doc.setTextColor(150);

  doc.text(

    "Generated by StudyHub",

    20,

    285

  );

  doc.save(`${note.title}.pdf`);

};